version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb_beach_api
    restart: unless-stopped
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - '27017:27017'
  server:
    build: .
    container_name: server_beach_api
    restart: unless-stopped
    entrypoint: ["yarn", "start", "APP_PORT=3000"]
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app
